test7 flake8

diff --git a/.github/workflows/python_lint.yml b/.github/workflows/python_lint.yml
--- a/.github/workflows/python_lint.yml
+++ b/.github/workflows/python_lint.yml
@@ -22,11 +22,15 @@ jobs:
       - name: Install flake8
         run: pip install flake8
       - name: Run flake8
-        uses: suo/flake8-github-action@v1
-        with:
-          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+      # fail if there are any flake8 errors
+      flake8 . --count --max-complexity=15 --max-line-length=127 --statistics
+
+      - name: Check if 'Lint with flake8' step failed
+        if: steps.flake8.outcome != 'success'
+        run: |
+          echo "flake8 fails"
+          exit 1
 
   black_lint:
     runs-on: ubuntu-latest
